### ISSUE TITLE
Align both status and reason to `flex-start`?

### ISSUE THREAD

**Issue by mewtaylor** [SecondLiners/GO2#221]
first of all – the new design looks awesome!

It looks like the status and reason for gigs in the new format are center-aligned (sort of), which I think might be a consequence of:
* The `div` that wraps around status/reason uses `inline-flex`, and defaults to aligning items on the center
* The text for the reason is not wrapped in an html, and the status circle is (as a `button`), and so the text is not being treated as an item to align
* The status button element has top padding and the text does not

It causes multi-line reasons to appear center-aligned, but one-line reasons to look off-center:
<img width="226" alt="screen shot 2018-05-11 at 1 58 49 pm" src="https://user-images.githubusercontent.com/1815772/39939725-2cdd4254-5525-11e8-86e3-67ccf93bae45.png">

*Note*: I am only seeing this for statuses that are not editable – my own status, since it's editable, looks vertically aligned correctly. 

If it's helpful – I'm on a Mac 10.13, Chrome 66.

**Comment by aaronoppenheimer** [comment]
Hi Matt,

I refactored the div's a bit, and forced vertical centering with style="display:flex; align-items:center;" - maybe there's a cleaner way?

I also noticed that the height of the icons (circles and squares) for other members was weird - turned out that was still using the "xs" size specification, which no longer exists. Should look much better; will roll it out tonight.

THANK YOU!!
